### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by JanoschMenke** [schwallergroup/saturn#3]
Hi Jeff,

just some minor bugs I noticed.

- The SlogP Component is not exposed, so it cannot be used in the config file.
- Both the jaccard and the `tanimoto_similarity`  component do not work properly, because of this line:

```
self.parameters.specific_parameters.get(self.component_specific_parameters.SMILES, [])
```

Should probably be or something right?

```
self.parameters.specific_parameters.get("reference_smiles", [])
```

I made these changes on my end but I am not sure if contributions are wanted.

**Comment by GuoJeff** [comment]
Hi Janosch,

Thank you for flagging this. I pushed a fix now.

And contributions are definitely welcome if you spot other bugs!

**Comment by JanoschMenke-deepmirror** [comment]
The spelling is not correct in `/oracle/utils.py` 
`from oracles.physchem.slogp import SLogP` should be `from oracles.physchem.slogp import SlogP`

**Comment by JanoschMenke** [comment]
Just a minor detail still. In oracle/utils.py SlogP is spelled with a capital L but should be written with a lower l as in `SlogP`

**Comment by GuoJeff** [comment]
Just made the change!

**Comment by GuoJeff** [comment]
Closing for now
